Add support for uncased
rust-phf/rust-phf pull request #197
Opened 2020-11-06 16:15 UTC by benesch

I suspect the `unsafe` in this PR may make this unmergeable, but figured I'd throw up anyway, because the current support for `UniCase` is sadly pretty useless, as far as I can tell. Details below, but basically AFAICT you can only perform lookups in a `UniCase` map if you have a static string literal.

----

uncased is an ASCII-only case insensitive comparison library like
UniCase, but it has better support for being used in a map.

Specifically, UniCase does not support the Borrow trait (see
seanmonstar/unicase#22), so the type

    phf::Map<UniCase<&'static str>, _>

only supports lookups with static string literals, which has limited
usefulness.

By contrast, the the equivalent uncased construction

    phf::Map<&'static Uncased, _>

*does* support lookups with non-static strings.

2021-06-08 15:46 UTC, JohnTitor commented
I'm happy to add uncased support as it's well-maintained compared with unicase.

> I suspect the unsafe in this PR may make this unmergeable

This `unsafe` means "we delegate the safety check to users" and it's the current best way to support, I think it's fine if we mention it as docs somewhere.

2021-06-08 16:06 UTC, benesch commented
Great! Anything you'd like me to do?

2021-06-08 18:32 UTC, JohnTitor requested changes
Also needs a rebase to resolve the merge conflict and to add a changelog entry. I'll take care of the doc part after merging (as I haven't figured out where's the best place) so don't worry about it.

2021-06-08 18:32 UTC, JohnTitor commented on phf_codegen/test/Cargo.toml
> +uncased = { version = "0.9.3", default-features = false }
This version is now yanked, should be 0.9.6 now.

2021-06-08 18:32 UTC, JohnTitor commented on phf_codegen/test/build.rs
> +
```suggestion
```

2021-06-08 18:32 UTC, JohnTitor commented on phf_codegen/test/src/lib.rs
> +
```suggestion
```

2021-06-09 02:54 UTC, JohnTitor commented
I've merged #174 and you should also implement the `PhfBorrow` trait for `UncasedStr`.

2021-06-11 15:20 UTC, JohnTitor commented
If you don't have some time to do them right now, feel free to let me know. I'm happy to take over.

2021-06-11 15:43 UTC, benesch commented
Ah yeah, sorry, on vacation until next week! I can handle it then but by
all means please feel free to take over.

On Fri, Jun 11, 2021 at 9:20 AM Yuki Okushi ***@***.***>
wrote:

> If you don't have some time to do them right now, feel free to let me
> know. I'm happy to take over.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sfackler/rust-phf/pull/197#issuecomment-859655832>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGXSIGZGNMDENJKQS2MEPLTSIST7ANCNFSM4TM3U4OA>
> .
>

2021-06-11 15:53 UTC, JohnTitor commented
Alright, I'll do if it's ready to make a new release until then. Have a great vacation!

2021-06-16 17:55 UTC, benesch commented
Ok, done!

2021-06-16 17:59 UTC, benesch commented
Hrm, seems like this might require an MSRV bump?

2021-06-16 18:18 UTC, benesch commented
Pushed up a rev that bumps the MSRV to 1.46.0. Hopefully that does it!

2021-06-16 18:30 UTC, benesch commented
And it's green!

2021-06-17 07:09 UTC, JohnTitor approved these changes

2021-06-17 07:10 UTC, JohnTitor commented
Looks great now, thanks!

2021-06-17 07:10 UTC, merged